### ISSUE TITLE
Inputs controlados e não-controlados

### ISSUE THREAD

**Issue by jvzaniolo** [bbarreto08/ReactJs-Learn#2]
# Desafio do desafio

Pesquise sobre inputs controlados e não-controlados no React e mude a implementação do componente `TaskForm` para ter acesso ao valor do input sem utilizar de estados.

Explique com suas palavras nessa Issue o que você aprendeu no processo.

## Linhas

https://github.com/bbarreto08/ReactJs-Learn/blob/caf34134be628a79930161ecf7dbfcd06d658b27/Desafios/todo-app/src/components/TaskForm/TaskForm.jsx#L5
https://github.com/bbarreto08/ReactJs-Learn/blob/caf34134be628a79930161ecf7dbfcd06d658b27/Desafios/todo-app/src/components/TaskForm/TaskForm.jsx#L36-L37

**Comment by bbarreto08** [comment]
No processo da

**Comment by bbarreto08** [comment]
Na primeira parte, está sendo declarado um estado controlado, ou seja, o "task" é um valor mutável que pdoe ser alterado ao longo do código com a chamada setTask, no exemplo em questão ele está sendo iniciado com um string vazia.

Já na segunda parte, é um exemplo do uso do estado task, onde a propriedade value está recebendo o valor do estado, e o elemento em questão toda vez que é alterado é executado a atualização do estado da "task".
